# Generated by Django 5.2.4 on 2025-07-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('code_engin', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('famille_engin', models.CharField(max_length=100)),
                ('capacite_max', models.FloatField()),
                ('etat_engin', models.CharField(choices=[('disponible', 'Disponible'), ('en maintenance', 'En maintenance'), ('affecté', 'Affecté')], max_length=20)),
                ('nombre_engin', models.IntegerField()),
            ],
        ),
    ]
