# Generated by Django 5.2.4 on 2025-07-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='engin',
            table='engins',
        ),
    ]
