# Generated by Django 5.2.4 on 2025-07-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_tech', '0002_alter_engin_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engin',
            name='nombre_engin',
        ),
    ]
