# Generated by Django 5.2.4 on 2025-07-29 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id_absence', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=30)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('id_shift', models.IntegerField()),
                ('date_debut_abs', models.DateTimeField()),
                ('date_fin_abs', models.DateTimeField()),
                ('justification', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('est_justifié', models.BooleanField()),
            ],
            options={
                'db_table': 'absences',
            },
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('engin_assigne', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id_shift', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut_shift', models.DateTimeField()),
                ('date_fin_shift', models.DateTimeField()),
            ],
            options={
                'db_table': 'SHIFTS',
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engin', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutention.conducteur')),
            ],
        ),
        migrations.CreateModel(
            name='ChefEscale',
            fields=[
                ('id_chef_escale', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nbr_aff_manuelle', models.IntegerField(default=4)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('id_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manutention.shifts')),
            ],
            options={
                'db_table': 'CHEF_ESCALE',
            },
        ),
        migrations.CreateModel(
            name='Conducteurs',
            fields=[
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conducteurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dockers',
            fields=[
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dockers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Engins',
            fields=[
                ('code_engin', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('famille_engin', models.CharField(max_length=30)),
                ('capacite_max', models.FloatField(blank=True, null=True)),
                ('etat_engin', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_engin', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'engins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnginsAffectees',
            fields=[
                ('id_engin_affectee', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'engins_affectees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_equipe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_equipe', models.CharField(blank=True, max_length=50, null=True)),
                ('chef_equipe', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_membres', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAffectations',
            fields=[
                ('id_historique', models.AutoField(primary_key=True, serialize=False)),
                ('date_modification', models.DateTimeField(blank=True, null=True)),
                ('ancien_etat', models.CharField(blank=True, max_length=20, null=True)),
                ('nouvel_etat', models.CharField(blank=True, max_length=20, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historique_affectations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id_incident', models.AutoField(primary_key=True, serialize=False)),
                ('date_incident', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gravite', models.CharField(blank=True, max_length=20, null=True)),
                ('matricule_conducteur', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'incidents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateur', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(blank=True, max_length=200, null=True)),
                ('date_action', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_adresse', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id_maintenance', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('type_maintenance', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maintenance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('destinataire', models.CharField(blank=True, max_length=100, null=True)),
                ('sujet', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('lu', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id_parametre', models.AutoField(primary_key=True, serialize=False)),
                ('nom_parametre', models.CharField(blank=True, max_length=100, null=True)),
                ('valeur', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parametres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualificationsConducteurs',
            fields=[
                ('id_qualification', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(blank=True, max_length=20, null=True)),
                ('niveau', models.CharField(blank=True, max_length=20, null=True)),
                ('date_obtention', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qualifications_conducteurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rapports',
            fields=[
                ('id_rapport', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.CharField(blank=True, max_length=100, null=True)),
                ('type_rapport', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'rapports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id_shift', models.AutoField(primary_key=True, serialize=False)),
                ('nom_shift', models.CharField(blank=True, max_length=20, null=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shifts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Superviseurs',
            fields=[
                ('id_superviseur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'superviseurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mot_de_passe', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilisateurs',
                'managed': False,
            },
        ),
    ]
