# Generated by Django 5.2.4 on 2025-07-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutention', '0001_initial'),
    ]

    operations = [
        # Migration pour mettre à jour la table absences
        migrations.RunSQL(
            # SQL pour mettre à jour la structure de la table
            """
            -- Supprimer l'ancienne colonne est_justifié si elle existe
            ALTER TABLE absences DROP COLUMN IF EXISTS est_justifié;
            
            -- Modifier la colonne etat pour ajouter les contraintes
            ALTER TABLE absences 
            ALTER COLUMN etat TYPE VARCHAR(20),
            ALTER COLUMN etat SET DEFAULT 'en attente';
            
            -- Supprimer la contrainte si elle existe déjà, puis la recréer
            ALTER TABLE absences DROP CONSTRAINT IF EXISTS absences_etat_check;
            ALTER TABLE absences ADD CONSTRAINT absences_etat_check 
            CHECK (etat IN ('en attente', 'validée', 'refusée'));
            
            -- S'assurer que la colonne uploaded_at existe et a le bon type
            ALTER TABLE absences 
            ALTER COLUMN uploaded_at TYPE TIMESTAMP,
            ALTER COLUMN uploaded_at SET DEFAULT CURRENT_TIMESTAMP;
            
            -- S'assurer que les autres colonnes ont les bons types
            ALTER TABLE absences 
            ALTER COLUMN date_debut_abs TYPE TIMESTAMP,
            ALTER COLUMN date_fin_abs TYPE TIMESTAMP,
            ALTER COLUMN justification TYPE TEXT;
            """,
            # SQL de rollback
            """
            -- Rollback: restaurer l'ancienne structure si nécessaire
            ALTER TABLE absences 
            ALTER COLUMN etat DROP DEFAULT,
            DROP CONSTRAINT IF EXISTS absences_etat_check;
            """
        ),
    ]
