# Generated by Django 5.2.4 on 2025-07-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutention', '0003_fake_absences_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absences',
            fields=[
                ('id_absence', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut_abs', models.DateTimeField(blank=True, null=True)),
                ('date_fin_abs', models.DateTimeField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('en attente', 'En attente'), ('validée', 'Validée'), ('refusée', 'Refusée')], default='en attente', max_length=20)),
            ],
            options={
                'db_table': 'absences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_equipe', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'equipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfoEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('fonction', models.CharField(blank=True, max_length=30, null=True)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('disponibilité', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'info_equipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AbsenceNonDeclaree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=30)),
                ('id_shift', models.IntegerField()),
                ('date_debut_abs', models.DateTimeField()),
                ('date_fin_abs', models.DateTimeField()),
            ],
            options={
                'db_table': 'absences_non_déclarées',
            },
        ),
        migrations.DeleteModel(
            name='Absence',
        ),
    ]
