# Generated by Django 5.2.4 on 2025-08-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutention', '0004_absences_equipe_infoequipe_absencenondeclaree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absences',
            name='fichier_justification',
            field=models.FileField(blank=True, null=True, upload_to='justifications/'),
        ),
    ]
