# Generated by Django 5.2.4 on 2025-08-04 10:53

import manutention.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutention', '0005_auto_20250801_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsencesNonDeclarees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=30)),
                ('id_shift', models.IntegerField()),
                ('date_debut_abs', models.DateTimeField(blank=True, null=True)),
                ('date_fin_abs', models.DateTimeField(blank=True, null=True)),
                ('est_justifie', models.BooleanField(default=False)),
                ('justification', models.FileField(blank=True, null=True, upload_to=manutention.models.justification_upload_path, verbose_name='Fichier de justification')),
            ],
            options={
                'db_table': 'absences_non_déclarées',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Affectations',
            fields=[
                ('id_affectation', models.AutoField(primary_key=True, serialize=False)),
                ('date_affectation', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'affectations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChefEscaleAvance',
            fields=[
                ('id_chef_escale', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chef_escale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CumulHeures',
            fields=[
                ('id_cumul', models.AutoField(primary_key=True, serialize=False)),
                ('heure_par_engin', models.FloatField(blank=True, null=True)),
                ('date_cumul', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cumul_heures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NavirePrevisionnel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('statut', models.CharField(max_length=50)),
                ('date_arrivee', models.DateField()),
                ('heure_arrivee', models.TimeField()),
                ('port', models.CharField(max_length=100)),
                ('consignataire', models.CharField(max_length=255)),
                ('operateur', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'navires_previsionnels',
                'ordering': ['date_arrivee', 'heure_arrivee'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='shifts',
            options={},
        ),
    ]
