# Generated by Django 5.2.4 on 2025-08-04 10:05:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Supprimer l'ancienne contrainte de choix si elle existe
        migrations.RunSQL(
            "ALTER TABLE utilisateurs DROP CONSTRAINT IF EXISTS utilisateurs_role_check;",
            reverse_sql=""
        ),
        # Ajouter une nouvelle contrainte avec les nouveaux rôles
        migrations.RunSQL(
            """
            ALTER TABLE utilisateurs 
            ADD CONSTRAINT utilisateurs_role_check 
            CHECK (role IN ('admin', 'CE', 'DT', 'RH'));
            """,
            reverse_sql="ALTER TABLE utilisateurs DROP CONSTRAINT IF EXISTS utilisateurs_role_check;"
        ),
    ] 