# Generated by Django 5.2.4 on 2025-08-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_user'),
        ('users', '0002_update_roles'),
    ]

    operations = [
    ]
